name: run my vanilla Cypress tests
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          browser: chrome
          
      - name: upload videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Cypress E2E Videos
          path: cypress/videos

      - name: upload mochawesome-report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Cypress E2E reports
          path: cypress/reports